resource_types:
- name: pull-request
  type: registry-image
  source:
    repository: teliaoss/github-pr-resource

- name: buildkit-resource
  type: registry-image
  source:
    repository: vito/oci-build-task

resources:

# - name: daily
#   type: time
#   icon: alarm
#   source:
#     location: Europe/Berlin
#     interval: 24h
#     start: 3:00 AM
#     stop: 5:00 PM

- name: recipe-rust-glibc-env
  type: git
  icon: git
  source:
    branch: master
    uri: git@github.com:drahnr/rust-containers.git
    private_key: ((sirmergealot-ssh-key))
    paths: [ Dockerfile.rustglibc ]

- name: recipe-rust-musl-env
  type: git
  icon: git
  source:
    branch: master
    uri: git@github.com:drahnr/rust-containers.git
    private_key: ((sirmergealot-ssh-key))
    paths: [ Dockerfile.rustmusl ]

- name: recipe-cxx-env
  type: git
  icon: git
  source:
    branch: master
    uri: git@github.com:drahnr/rust-containers.git
    private_key: ((sirmergealot-ssh-key))
    paths: [ Dockerfile.cxxenv ]

- name: env-rust-musl
  type: registry-image
  icon: docker
  source:
    tag: latest
    repository: quay.io/drahnr/rust-musl-builder
    username: ((quay-drahnr-username))
    password: ((quay-drahnr-password))

- name: env-rust-glibc
  type: registry-image
  icon: docker
  source:
    tag: latest
    repository: quay.io/drahnr/rust-glibc-builder
    username: ((quay-drahnr-username))
    password: ((quay-drahnr-password))

- name: env-cxx
  type: registry-image
  icon: docker
  source:
    tag: latest
    repository: quay.io/drahnr/container-cxx-env
    username: ((quay-drahnr-username))
    password: ((quay-drahnr-password))

jobs:
  - name: create-rust-musl-env
    build_logs_to_retain: 5
    public: true
    serial: true
    plan:
    - get: recipe
      resource: recipe-rust-musl-env
      trigger: true

    # - get: timed-trigger
    #   resource: daily
    #   trigger: true

    - task: build-rust-musl-env
      privileged: true

      config:
        platform: linux

        image_resource:
          type: registry-image
          source:
            repository: concourse/oci-build-task

        # TODO caching!
        params:
          DOCKERFILE: recipe/Dockerfile.rustmusl
          CONTEXT: recipe

        inputs:
        - name: recipe

        outputs:
        - name: image

        run:
          path: build

    - put: env-rust-musl
      params: {image: image/image.tar}

  - name: test-rust-musl-env
    build_logs_to_retain: 5
    public: true
    serial: true
    plan:
    - get: env-rust-musl
      trigger: true
      passed: [create-rust-musl-env]

    - task: test-rust-musl-env
      image: env-rust-musl
      config:
        platform: linux
        inputs:
        - name: env-rust-musl

        run:
          path: sh
          args:
          - -exc
          - |
            rustc --version
            cargo init --bin testy
            cd testy
            cargo build

  - name: create-rust-glibc-env
    build_logs_to_retain: 5
    public: true
    serial: true
    plan:
    - get: recipe
      resource: recipe-rust-glibc-env
      trigger: true

    # - get: timed-trigger
    #   resource: daily
    #   trigger: true

    - task: build
      privileged: true

      config:
        platform: linux

        image_resource:
          type: registry-image
          source:
            repository: concourse/oci-build-task
        params:
          DOCKERFILE: recipe/Dockerfile.rustglibc
          CONTEXT: recipe

        inputs:
        - name: recipe

        outputs:
        - name: image

        run:
          path: build

    - put: env-rust-glibc
      params: {image: image/image.tar}


  - name: test-rust-glibc-env
    build_logs_to_retain: 5
    public: true
    serial: true
    plan:
    - get: env-rust-glibc
      trigger: true
      passed: [create-rust-glibc-env]

    - task: test-rust-glibc-env
      image: env-rust-glibc
      config:
        platform: linux
        inputs:
        - name: env-rust-glibc

        run:
          user: sirmergealot
          path: sh
          args:
          - -exc
          - |
            sudo chown $(whoami): -Rf .
            rustup which rustc
            rustup default
            rustc --version
            cargo init --bin testy
            cd testy
            cargo +stable b
            cargo +beta b
            cargo +nightly b

  - name: create-cxx-env
    build_logs_to_retain: 5
    public: true
    serial: true
    plan:
    - get: recipe
      resource: recipe-cxx-env
      trigger: true

    # - get: timed-trigger
    #   resource: daily
    #   trigger: true

    - task: build
      privileged: true

      config:
        platform: linux

        image_resource:
          type: registry-image
          source:
            repository: vito/oci-build-task

        params:
          DOCKERFILE: recipe/Dockerfile.cxxenv

        inputs:
        - name: recipe

        outputs:
        - name: image

        run:
          path: build

    - put: env-cxx
      params: {image: image/image.tar}
