FROM quay.io/drahnr/rust-musl-builder

LABEL maintainer="Bernhard Schuster <bernhard@ahoi.io>"

USER root

ENV CMAKE_MAKE_PROGRAM=make

RUN dnf -y install \
	musl-clang \
	musl-gcc \
	musl-libc-static \
	musl-libc \
	musl-devel \
	musl-filesystem


RUN rustup toolchain install \
        stable-x86_64-unknown-linux-musl \
        beta-x86_64-unknown-linux-musl \
        nightly-x86_64-unknown-linux-musl
RUN rustup component add clippy
RUN rustup default nightly-x86_64-unknown-linux-musl
