
FROM alpine:edge

MAINTAINER Bernhard Schuster "bernhard@ahoi.io"

RUN apk add build-base gcc abuild binutils curl \
     cmake extra-cmake-modules git \
     alpine-sdk autoconf automake libtool \
     bash linux-headers

ENV CMAKE_MAKE_PROGRAM=make